language: node_js
sudo: required
notifications:
  email: false
dist: focal
node_js:
  - 18
install:
  - npm ci
jobs:
  include:
    - stage: Lint
      script: npm run lint && commitlint-travis
    - stage: Test
      script:
        - 'npm run test && npm run test:ct && npm run build'
        - 'curl -Os https://uploader.codecov.io/latest/linux/codecov && chmod +x codecov'
      after_success: ./codecov -cF jest && ./codecov -cF cypress
env:
    global:
    - BRANCH=${TRAVIS_PULL_REQUEST_BRANCH:-$TRAVIS_BRANCH}
